env:
  global:
    - # GITHUB_SECRET_TOKEN
    - secure: "ajJ1A26mzEJ1yiJrbXn3QYPMyy0wH/tzF4XsX54t3v9wdvHF/dqYWvAB1YW3yANqYC6ET7H/Oj4vcDpQ6ah+AvF3ksBsYphRA5jsJsLp6u5Hbhsm3a973Fym1reF/kgO0U+IaQDa4V3r2SqU4xEDr1lVs1sQn+sSMg0cMAuL7tbmNCJrhUIXz9OFEYR4I9X+1Muyxes+zkbG+T1oRDU7aSHmz8w4AEpivD0kAV4w7TIjgtHIndn2XeUircK6lr26HuXe2pxNQnwPx5K/7iqe170kwjLOhp41sJ/gjcrUkZP2Jc5VF/uMdhtDPZ+3+tI7f7uPkGWHZBwQNM92uZb4ADuZDgdfzRat8qUMpGCYpr1IvCBdONNX21Ovyw3yHzGoRSW0qm3aRBJRPhrgtcWN3JR37kvs4K+5c8cF2HYnJzKW3xfesrl+uEqRgJG8PkBBclXWWK1Z2BHSVRzOCTYCIhNFeoXeXdDru+0kPLIA5EoSZqosRDyH7UVHtE4wYjPPYZrSaIYUTsy8Jy5470csZDkO9Dt7vU+QePND8TxAc0S63c9Ya9koFKaGRQQn0Mqlic9FZlS5fXuv96Ln+GgIt3DUOYhRrvYzTEvEysjX/YenF65rOv0lCWlbkpOA5MFJzla15eVe7cQbZ7jrpw5BK5mW+8ul0eP6U75epUPGAkA="
    - # SONATYPE_USERNAME
    - secure: "cT+5eIUMW3IDWZ5/KyInxKwI6volF4J31YNkonarny4XnTUUQXpOOQza8sUymqr/rC0E3MrvPcdPAQccwVqmdT7lco3VDpidMbrkZMmWCNvaQyYeDzWmypbyJ02dN4ATdC2b40HwFND3SIl/YCIQ6hPROebJSTUz2ohIoRfUNDOddUGUX3H8W5Q6pwLvr3YlwHU8HUNADKly4SwBOwmFJIhQ/oQ7cwcXODv0bsGiaLbsn1cVXioQB9zsfz0jmUWhVDMF4fGy8BRXlCg0DjUpS72Voom0lVLF/S6NrLUITnmvVGg/eRNveTwhf+nP3Ul6MkSxEspm0rwqnein6OHNHMbOxqC+Ocx2qvA7WBT+cZ3egakrDSHFjhQwENoAcnWwZCoaaca9bKPkallMuSds+jnlJWOLSW3T0fD8xJx1jOCpKgosygy+U7rszlQhC9IGFPm/G1XqSfyFHsotBbMntS4cAzKWieFl3NljCf1m8Ek4B5Ex6EJNqx7FvxtAvvsYGsfoqrsu8mdKP3K/2rZ2ZgQH2BdXW8e+gZouecsTybGkvU49sscVJR/Dzhc0iPIQtq34gbCEUXCHakQVY5H1RzdNNxzRRhlogseX8nObo4qaeUYxGj3Ftg3GT9JQaxMLILtkKMOI1ydbijT/u9hzzy71y/MCXlM9n+z5R4IBCrg="
    - # SONATYPE_PASSWORD
    - secure: "hAfhvxjFDe10wy7UtyCSAH9GlN5AyLMthxQvrT6HGzVyzl52YGo0EAyRFfUY0wxFo6aNJKIKyfqX0BGBEDf+KypDAEq9K6X39TsFjLd2jmq04JFlH4RkvIbVjIqwd/aV18raJxJB6keTaKDTtW/lLGXRw/DFAN7oyjnKvzlA7XNNI2e8welzBvupzaSsubue0fy+C1WA3QjAzqygcjORn5ey6oOxz+uFJGXgLozerB1PaNt0eB8daTMiGZgHbGwlB2XvbrpKLh8VOclaXoC+dbO41WXSilxVDo2RnbFzffpBUjhwWRkz88dkDtjMS/8qEZphjhFPL3kV09UPvIfEUIN7bfftbsUfrTZD8HwEny1dvVsp0qwPnopM5SEYt4ai8V5VpwqbaSjv9YIsmIMSImdeFw/Pz+I559ucWyPT6z5OTcirbigeSSt7b7hCzwle8fVaiD824zMgV87hc3K8hkf65n4DsXdyJ6ZDT6DQpekgtQgG9Yo/71sVn5OzbKIuIXIa85fevYZl9dSPJxnlARjok2y5O8qYwh5ShItVxGf4IqOq3mOOMRTlt5h2qKOS5mG/a+Mzig6xOT4y0LFFSTOq6XTtvnceZPJg1RAcEnPuZonw+1pFLoB0ZUAqehqLRN/FSmA1mlpWB6p1DcJcNhtQ6xlg3nITiNuqANQhREg="
    - # GPG_KEY_ID
    - secure: "MN6gVxAdlZw4GCmiybPGHQh3BIPFtCUoq2Pg4wFBDA0yrfatAPW/OOERvmBbzWp5N7s5Nm82Vr+3ebUcHJrtihV56Z2YUJWed+dW4UoUqP0y2t9imdjzwrVYZb10BQKLm4Tp8a2tNCkP0M54F7D+lywmN26ohDdI0ydTmatdr7dMTaNLI2i0poCX2lTejm6dow2yc3usQF8bsZMrKyIC5AvTS1UyZdiv8Cirn/rL9art97TbgpbEg906PTfT4q8GC7in9HkIUQUKW7QF4dIbGkLDdl1bxMw2YWf2chciqfYTcBVuE5vK2BjWf4pleZ/thVIwS6gfWnZ1oxuCdva+e3Ffk9K8hCVT2vTjsbuXkt/NgOx+eYiPBRFsSevw0+zr8TVc7clI4195gMFfo32rdzIypJYGihfsYNU5TDy6WNE6qrNT0C6E+06aTDwPOvDeDRmma1+hk11yltc0+5s+5cwNEy9a2r15gCvZZoK7rPWckzgcLrPcR109LE61qiLbY64Hvn0L+VI+pTAEgYa7+7Ic2GTqutzk1IMCNEP4Kziqgrh/JGGu784a1cC1YUGjlHkaegiMIOczGHfkWvHQ5kE6hu7cELTTyeXW8D2dgqvFITA26XYZ0Kd1ibTwa4Dwr3e8Jl+jroVq9cxn4tRA6CWow3UxFqon2npYZ2pgsRM="
    - # GPG_PASSPHRASE
    - secure: "VTV9pENhM2t1aO9Vx22hD5P72susbrZAh0ZLYailcgVGeA1rqUtf0xEgCZuVfNjePc6XCA5vh0IJMHmOptPo+/5adOoZxaq+qtI6JwahpGPypZfYQlFhy/GELNY8WGvZ9A1s1b/6Glbdq7c++RcN3mTmiwLTaWXNvTCWYF9BtDLthpZinwwUf27Ap00yVVVPEJ0zifcLaM0W0oesUCZAagcEB25P4moBFmXNkWfX63Ef1Gyfkung8/zZVsWdKvHx9ArGyipMIGu9LyV5hMci80qxmTc0nmUW8svBqRWB09szmkKdgCdqeBnFTLrXEXr6nqB3gjQKyQtGz91jOxBguzVgCBb8KlXNJGVyph99tzP+zEu5uqdjDk7ilIQrDETLlJ3quLmvaYAHxIyk1KiN6WUmwhYo0ni+qMjxEDy1ghTbQmXlcYyj4Ia+Dz9qfZMk8zrV5HqffVm6i2kss0GBLCJlhvvFv54qwqoJuI+hEt9Ocs5NKKiuPqI1SVUJzWLem4uLP8bwDa13jgVxb6LWNmNBMOyZxN0iNqMpI9yjbsg84IgDESMtF9x87MR3Vk0gTwOyseKc6hbTuhjNtcQfLJIboPfP3j30bAe7CQTKng1pxngWOLCEsruE3SXc5/Lo/3TBm8PS+22U1Zm3TG3EBFS9jpKOBnz3/HbaUf8Y2ak="
    - GPG_KEY_LOCATION=".travis/secring.gpg"
    - ENCRYPTED_GPG_KEY_LOCATION=".travis/secring.gpg.enc"

branches:
  only:
  - master
  - dev
  - /^v\d+\.\d+(\.\d+)?$/

# Default settings for build stages
language: java
jdk:
  - openjdk8
  - oraclejdk8
  - oraclejdk9
install:
  - chmod ug+x .travis/*.sh
  - .travis/install.sh
script: .travis/build.sh

# Build stages
jobs:
  include:
    - stage: i18n
      language: python
      python: "3.6"
      # Install Transifex client v0.13.1
      install: pip install git+https://github.com/transifex/transifex-client.git@08deb1255de7217d2574e3c49dcb578f03b195e0#egg=transifex-client
      script: ./gradlew generatePot
      after_success: |
        if [ ! -z "$TRANSIFEX_TOKEN" ]; then
          tx --token="$TRANSIFEX_TOKEN" --force-save --no-interactive init
          git checkout HEAD .tx/config
          tx push -s --no-interactive
        fi
    - stage: merge dev to master
      script: .travis/merge-dev-to-master.sh
    - stage: tag master
      script: .travis/tag-master.sh
    - stage: GitHub release
      script: ./gradlew build
      env: MANUAL_RELEASE_TRIGGERED=true
      deploy:
        api_key: $GITHUB_SECRET_TOKEN
        file_glob: true
        provider: releases
        skip_cleanup: true
        file:
          - "build/libs/*"
          - "build/dist/josm-atlas.jar"
          - "build/tmp/jar/MANIFEST.MF"
        on:
          tags: true

# Order and conditions for build stages
stages:
  - name: test
  - name: i18n
    if: branch = master AND type = push AND repo = osmlab/josm-atlas
  - name: merge dev to master
    if: branch = dev AND type = push AND repo = osmlab/josm-atlas
  - name: tag master
    if: branch = master AND type = push AND repo = osmlab/josm-atlas
  - name: GitHub release
    if: tag IS present AND type = push AND repo = osmlab/josm-atlas
